export const TEAMS = [
  'Al-Hilal',
  'Al-Nassr',
  'Al-Ittihad',
  'Al-Ahli',
  'Al-Shabab',
  'Al-Ettifaq',
  'Al-Taawoun',
  'Al-Fayha',
  'Al-Fateh',
  'Al-Raed',
  'Damac',
  'Al-Khaleej',
  'Al-Riyadh',
  'Al-Wehda',
  'Al-Okhdood',
  'Al-Qadsiah',
  'Al-Kholood',
  'Al-Orobah',
  'Al-Hazem',
  'Abha',
  'Al-Tai',
  'Al-Batin',
  'Al-Adalah',
  'Al-Faisaly',
] as const;

export const PLAYERS = [
  'Mohammed Al-Dawsari',
  'Salem Al-Shehri',
  'Firas Al-Buraikan',
  'Saleh Al-Ghannam',
  'Abdullah Al-Hamdan',
  'Sami Al-Najei',
  'Mohammed Kanno',
  'Nasser Al-Omran',
  'Khalid Al-Ghamdi',
  'Fahad Al-Muwallad',
  'Sultan Al-Anazi',
  'Turki Al-Ammar',
  'Hassan Al-Tambakti',
  'Ali Al-Bulaihi',
  'Abdulelah Al-Amri',
  'Saud Abdulhamid',
  'Nawaf Al-Aqidi',
  'Ziyad Al-Sahafi',
  'Ayman Yahya',
  'Abdulrahman Ghareeb',
  'Haroune Camara',
  'Karim Benzia',
  'Odion Martins',
  'Anderson Talisca',
  'Georges Wilson',
  'Milos Petrovic',
  'Jean-Luc Moreau',
  'Andre Carrillo',
  'Moussa Diaby',
  'Romain Saiss',
] as const;
